type: handshake
auth:
  handler: none
  cookie_url: https://school.joinhandshake.com
  required_cookies:
    - session_id
extractors:
  - url: https://school.joinhandshake.com/edu/analytics/reports/12345
    extracts:
      - type: query
      - type: explore
        prefix: "generated_handshake_production::"
        explore_name: students
      - type: model
  - url: https://school.joinhandshake.com/edu/analytics/reports/67890
    extracts:
      - type: query
